# Generated by Django 5.0.14 on 2026-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee_id', 'date'], name='attendance__employe_08d913_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['-date'], name='attendance__date_38ed57_idx'),
        ),
    ]
